### ISSUE TITLE
RoadMap: Version 3 Release

### ISSUE THREAD

**Issue by KaoruDev** [SiftScience/sift-ruby#39]
- [ ] Custom Error Hierarchy so that it is easier to rescue from exceptions generated from the gem vs ruby exceptions.
- [ ] Allow client to change endpoint URL, right now it's difficult to instantiate a client and have it point to our test boxes #40 
- [ ] Remove support for Rubies < `2.1` due to lack of support from the community (https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/)
- [ ] `Response` should be moved into it's own file. It should also have access to the original request for debugging purposes.
- [ ] Better handling of errors thrown when sending a request. #47

**Comment by exAspArk** [comment]
Hey @KaoruDev,

Are you planning to release `V3.0.0.0` to https://rubygems.org?

cc @admiral-akk

**Comment by KaoruDev** [comment]
I'm gonna defer this to @admiral-akk, as the features in this issue have been de-prioritized. Closing this for now.
